### ISSUE TITLE
multi process read from db issue

### ISSUE THREAD

**Issue by fatchan** [eslachance/enmap-rethink#6]
Hi, 
I'm using this module to store some JSON data that i have in memory to rethinkdb but am having an issue with multiple processes.
When I get, modify, then set, it works great in writing to DB. But it seems like when using multiple processes (using pm2 cluster mode of a node app i wrote), each process only reads the db tuples once,  modifies in memory with the get/set methods and writes what changed to the DB. 
This means if I have a DB for caching purposes of some data, one worker will .set, but the others do not read from the db when doing the next .get on the same key.

e.g.
worker 1
`someEnmap.set(1, "apple");
someEnmap.get(1); // => "apple"
`
worker 2 (after writing to DB has occured)
`someEnmap.get(1); // => undefined
`

Should I just be interacting with the databse directly intead? Also, wouldn't this mean that if I'm using enmap for a discord bot, different shards would load the entire database into memory rather than just getting data it needs per shard, resulting in high memory use?

Kind regards.

**Comment by eslachance** [comment]
This is an unfortunate limitation of the current version of Enmap, it doesn't get updates from the database. In order to maintain consistency between modules, implementing a method to syncronise every instance would require quite a bit of work, as not all databases have "stream" capabilities to get updates. 

As for your second question, by default yes the whole database is loaded. However, there *is* a way to load nothing and either get keys when necessary, or fetch an array of keys that you want to load (such as, for instance, an array of guild IDs for that shard). I sort of didn't document that part though, but if you look at the source code for the `enmap` module you'll see the methods and the option you can use for that. I'll document it when I get a chance.
